spring:
  datasource:
    url: "jdbc:postgresql://postgres5495:5495/fraud"
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    showSql: true
    hibernate:
      ddlAuto: update
  cloud:
    function:
      definition: fraudCheckEventConsumer
    stream:
      defaultBinder: kafka
      bindings:
        resultFraud-out-0:
          destination: result-fraud
          content-type: application/json

        fraudCheckEventConsumer-in-0:
          destination: check-fraud
          content-type: application/json
          group: fraud-service-group
      kafka:
        binder:
          brokers: kafka:9092

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
eureka:
  client:
    service-url:
      defaultZone: "http://discovery-server:8888/eureka/"
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}