spring:
  datasource:
    url: "jdbc:postgresql://localhost:5421/transfer"
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    showSql: true
    hibernate:
      ddlAuto: update
  cloud:
    function:
      definition: transferResponseConsumer;transactionEventConsumer
    stream:
      defaultBinder: kafka
      bindings:
        transfer-out-0: #bu binding mesajları transfer-money topic gönderir
          destination: transfer-money
          content-type: application/json

        transactionEventConsumer-in-0:
          destination: transaction-completed-topic
          content-type: application/json
          group: transfer-service-group
      kafka:
        binder:
          brokers: localhost:9092

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8888/eureka/"
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
